/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 samsung.gltf
Author: Agustín Hönnun (https://sketchfab.com/Agustin_Honnun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-phone-86bc31adcf1c43a085a29b350b03984d
Title: Mobile Phone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/samsung.gltf')
  return (
    <group {...props} dispose={null}>
      <group  scale={3}>
        <mesh geometry={nodes.Plane001_Metallico_0.geometry} material={materials.Metallico} />
        <mesh geometry={nodes.Plane001_Diffuse_0.geometry} material={materials.Diffuse} />
      </group>
    </group>
  )
}

useGLTF.preload('/samsung.gltf')
